apiVersion: apps/v1
kind: Deployment
metadata:
  name: uberapp-deployment
spec:
  replicas: 1  # Number of desired replicas
  selector:
    matchLabels:
      app: uberapp
  template:
    metadata:
      labels:
        app: uberapp
    spec:
      containers:
      - name: uberapp
        image: haywise/uberapp:latest
        ports:
        - containerPort: 3000  # Port your application listens on

